- README.md
- search_gov_crawler/scrapy_scheduler.py
- tests/search_gov_spiders/test_scrapy_scheduler.py
- Allows for apscheduler-backed process to schedule and run `scrapy crawl` commands directly, without scrapyd or scrapydweb.  This approach does not add any new requirements nor does it break anything related to running scrapyd or scrapydweb.
- Updated readme and added a few basic tests.
- Follow directions in main readme to start scheduler.  This will schedule all jobs according the the initial schedule specified in the [utilitiy files readme schedule](https://github.com/GSA/searchgov-spider/blob/main/search_gov_crawler/search_gov_spiders/utility_files/README.md#job-schedule-calendar). 
- You can now wait for the next scheduled run to ensure things work.
- If you don't want to wait you can try to schedule some test crawls by editing the `scrapy_scheduler.py` file to load crawl sites from …
> SRCH-5588 Scrapy Scheduler

- search_gov_crawler/scrapy_scheduler.py
- After the discussion on #48 and running some more tests locally, I think we should update the max workers for the threadpool to be the module default for concurrent.futures.  Apscheduler forces this to be 10 and while I could have subclassed the ThreadPoolExecutor class to add this custom __init__ method, i thought it more clear to hard code the latest default value here.  See https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor for details.
- Locally, this changes values from 10 to 16 and I noticed a **big** difference in performance.
- This line is executed in unit tests but you can also run the scheduler using any of the methods in #48 
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before …
> SRCH-5678 update max_workers

- search_gov_crawler/benchmark.py
- search_gov_crawler/scrapy_scheduler.py
Created this draft PR to help facilitate bench marking... what about something like this? gives us some flexibility?
```
python search_gov_crawler/benchmark.py --starting_urls="https://quotes.toscrape.com" --allowed_domains="quotes.toscrape.com"
```
This will add a job using a similar process as would with the no-UI functionality (and also scrapydweb I think) but we can control what we pass in.
If we need more configurable options we can add more environment variables or add a config file.
> SRCH-5714 add ability to do a single benchmark run

- search_gov_crawler/search_gov_spiders/extensions/json_logging.py
- search_gov_crawler/search_gov_spiders/middlewares.py
- search_gov_crawler/search_gov_spiders/settings.py
- search_gov_crawler/search_gov_spiders/spiders/domain_spider_js.py
- tests/search_gov_spiders/test_extensions.py
* Made updates and re-organized main `settings.py` so that:
* Settings adjusting similar high-level behavior are next to each other in the file
* Commented out a few settings that did not apply because the main flag for that setting is disabled.
* Disabled the [telnet console](https://docs.scrapy.org/en/latest/topics/telnetconsole.html) since we are not using it, I don't see us starting to use it.  Disabling it likely frees up some memory/CPU that can be used elsewhere.
* Disabled the close spider extension since I think we want to make sure we crawl every link available and don't want to stop crawling prematurely.
* Enforced a one second delay between requests and a single concurrent connection.
* Moved all playwright related settings to the `domain_spider_js` spider to prevent any usage …
> Srch 5744 benchmark findings

- search_gov_crawler/search_gov_spiders/pipelines.py
- search_gov_crawler/search_gov_spiders/settings.py
- tests/search_gov_spiders/test_full_crawl.py
We needed to disable to feed exporter (to do this just remove it from the settings.py) so that when the spiders run in parallel the extra file is not written to superfluously. 
Added file lock for writing to the all-links Item pipeline. 
Each spider will write to it's own all-links csv (which means each job has it's own file). Many spiders will not hit the 3.9MB limit but this will allow future work to immediately send the results (completed csv file) as the spider/job closes without waiting for the file to fill up for a new spider to populate it.  
When you run a benchmark test make sure no file is being written to search_gov_crawler/scrapy_urls/domain_spider or search_gov_crawler/scrapy_urls/domain_spider_js. Only the all-links csvs should be created now. 
Please ensure you have …
> SRCH-5748-Update-Spider-FEEDS-Setting

- README.md
- search_gov_crawler/benchmark.py
- search_gov_crawler/scrapy_scheduler.py
- search_gov_crawler/search_gov_spiders/utility_files/crawl-sites.json
- search_gov_crawler/search_gov_spiders/utility_files/crawl_sites.py
- search_gov_crawler/search_gov_spiders/utility_files/import_plist.py
- tests/search_gov_spiders/conftest.py
- tests/search_gov_spiders/crawl-sites-test.json
- tests/search_gov_spiders/test_benchmark.py
- tests/search_gov_spiders/test_crawl_sites.py
- tests/search_gov_spiders/test_deduplicator_pipeline.py
- tests/search_gov_spiders/test_scrapy_scheduler.py
- tests/search_gov_spiders/test_utiliity_files.py
- Since the "naive" scheduler implemented in `search_gov_crawler/search_gov_spiders/utility_files/init_schedule.py` is not optimal for a polite spider, we need to design something else.  Additionally, I wanted it to be more flexible.  To that end I added a "schedule" field in the crawl-sites.json file that holds a cron expression that can be fed, as-is, into the scheduler.  A record will now look like:
```json
{
"name": "DOD Army MWR",
"allow_query_string": false,
"allowed_domains": "armymwr.com",
"handle_javascript": false,
"schedule": "00 14 * * MON",
"starting_urls": "https://www.armymwr.com/"
}
```
With each row defining when and how often that domain will run -- in this case every Monday at 2pm UTC.  We can make changes and redeploy as needed.  I added some dataclasses to help …
> SRCH-5745 Scheduler Update

- search_gov_crawler/search_gov_spiders/pipelines.py
- tests/search_gov_spiders/test_urls_files_size.py
* Lowered the limit to 100KB and changed the name to MAX_URL_BATCH_SIZE_BYTES to better describe what it is now.
* Added type hints to the pipeline class and methods
* Added a test to verify the limit is working properly
*  Started to add one for file rotation but we are mocking so much with the files it was getting to be too much. We can always revisit.
A few different tests are possible.  To test the API usage, I found a free service that lets you POST to it and it returns what you sent back.  Thought this could be helpful to verifying number of requests.
**No Rollover - File**
Remove all old files and make sure the env var is not set.  Run a sample crawl:
```
cd search_gov_crawler
rm output/all-links*.csv
unset SPIDER_URLS_API
scrapy crawl domain_spider -a …
```
> SRCH-5795 lower limit for rotating files and batching POST requests

- cicd-scripts/app_install.sh
- cicd-scripts/app_start.sh
- cicd-scripts/app_stop.sh
- cicd-scripts/helpers/run_without_ui.sh
- cicd-scripts/helpers/update_pythonpath.sh
- Purpose of this is to fix build issues found in deployment log:
```
[2025-01-21 21:10:59.371] [d-NQI9CNY3M][stdout]Purging pip cache...
[2025-01-21 21:11:00.462] [d-NQI9CNY3M][stderr]rm: cannot remove '/root/.cache/pip': Permission denied
...
[2025-01-21 21:11:00.483] [d-NQI9CNY3M][stdout]Force killing remaining scrapy background jobs...
[2025-01-21 21:11:00.494] [d-NQI9CNY3M][stderr]
[2025-01-21 21:11:00.494] [d-NQI9CNY3M][stderr]Usage:
[2025-01-21 21:11:00.494] [d-NQI9CNY3M][stderr] kill [options] <pid> [...]
[2025-01-21 21:11:00.494] [d-NQI9CNY3M][stderr]
[2025-01-21 21:11:00.494] [d-NQI9CNY3M][stderr]Options:
[2025-01-21 21:11:00.494] [d-NQI9CNY3M][stderr] <pid> [...]            send signal to every <pid> listed
...
[2025-01-21 21:12:03.302] [d-NQI9CNY3M][stdout]Failed to install …
```
> Fix Build Issues

- cicd-scripts/helpers/update_pythonpath.sh
- Small fix to remove mismatched quote from PYTHONPATH 
> build-fix remove extra quote from new pythonpath

- search_gov_crawler/search_gov_spiders/settings.py
- tests/search_gov_spiders/test_full_crawl.py
Added the DEPTH_LIMIT of 3 to spider settings to limit the amount of urls scraped for first pass. 
Currently tests are failing. Going to edit tests to see if depth limit is set it should expect a lower number . 
Needs the ansible playbook PR to set the DEPTH_LIMIT var. But a default is provided here. 
> SRCH-5823-Scrapy-Depth-Limit

- search_gov_crawler/search_gov_spiders/utility_files/crawl_sites.py
- tests/search_gov_spiders/test_crawl_sites.py
**Built on PR 87**
Added the field "output_target" to the import_pylist.py file with value "endpoint". All of the domains grabbed from the plist are scrutiny domains that we want to put directly into elastic search. Values from Bing will have a target of "elastic" 
This goes through the rest of the code and takes the field through creation of jobs etc. 
Testing; 
- Updated the test found at `pytest tests/search_gov_spiders/test_crawl_sites.py` which should pass
- You can follow the directions to use the (import_pylist script) [https://github.com/GSA-TTS/searchgov-spider/tree/main/search_gov_crawler/search_gov_spiders/utility_files] also written below 
```
$ cd search_gov_crawler/search_gov_spiders/utility_files
$ python import_plist.py --input_file ./scrutiny-2023-06-20.plist
```
The new …
> SRCH-5827-Additional-Validation

- search_gov_crawler/benchmark.py
- search_gov_crawler/scrapy_scheduler.py
- tests/search_gov_spiders/test_benchmark.py
- tests/search_gov_spiders/test_scrapy_scheduler.py
I started this PR because in `search_gov_crawler/benchmark.py` i noticed that
`job_defaults={"coalesce": True, "max_instances": 1, "misfire_grace_time": True},`
when it should be
`job_defaults={"coalesce": True, "max_instances": 1, "misfire_grace_time": None},`
The `misfire_grace_time` argument allows the jobs to queue and run when slots are open.  The values must be a positive integer or None.  When its True it does not allow jobs to queue, it just runs the first number of jobs and then stops.  See https://apscheduler.readthedocs.io/en/3.x/userguide.html#missed-job-executions for more details.  Seems to me like it should error but, whatever, not my API.  I also added a test that will break if someone changes these configs
I wanted to add the same check for `scrapy_scheduler.py` but it …
> Misfire grace time bug

- appspec.yml
Our current CICD CodeDeploy pipeline times out while installing python 3.12, so it needs at lease more than 30min
> Increased CICD CodeDeploy timeout

- search_gov_crawler/elasticsearch/convert_html_i14y.py
In dev i have been seeing a lot of messages like these:
`error not enough image data while fetching: https://www.usgs.gov/themes/custom/usgs_tantalum/favicon.ico`
`error while fetching: https://home.army.mil/imcom-europe/5915/4824/7604/Box_MWR.jpg`
They all stem from the `newspaper.image_extractors` module.  That got me thinking, why are we trying to fetch these?
In the [configuration settings](https://newspaper4k.readthedocs.io/en/latest/user_guide/api_reference.html#configuration) there is an option to turn off this behavior.
Looking through the rest of the options, I think there are a few we could try eventually to reduce cpu or whatever but one that stood out is the `clean_article_html` option.  We are not using the output of this field so we don't need to clean it.
I looked through …
> SRCH-5861 Add config for newspaper to limit unnecessay actions

- search_gov_crawler/search_gov_spiders/helpers/encoding.py
- search_gov_crawler/search_gov_spiders/utility_files/crawl-sites-production-scrutiny.json
- search_gov_crawler/search_gov_spiders/utility_files/crawl-sites-production.json
- search_gov_crawler/search_gov_spiders/utility_files/import_plist.py
- tests/search_gov_spiders/test_crawl_sites.py
- Addresses two recurring errors in prod:
- Removes `diversity.nih.gov` from the scrutiny lists
- Adds support for VISCII encoding
- For the VISCII support, it appears that python does not support this but does support both unicode and cp1258 which according to wikipedia https://en.wikipedia.org/wiki/VISCII are close but may be missing some characters.  I guess if we actually try to index this we may miss some characters.  This is an "endpoint" domain however so we are just passing the URL to search anyway.  I originally had it defaulting to unicode in this case but decided on a Vietnamese-specific code page.  If we run into more issues with indexing this content I think we should revisit. 
- For the domain removal just verify that the domain has been remove from the apropriate lists
- …
> SRCH-5855 Prod Errors

- pyproject.toml
- search_gov_crawler/elasticsearch/es_batch_upload.py
- search_gov_crawler/search_gov_spiders/settings.py
- tests/search_gov_spiders/test_elasticsearch.py
- This PR is meant to address deficiencies in logging when we encounter an error loading data to elasticsearch.  Prior to these change you might see something like `"Failed to load 50 records to Elasticsearch"` as the entire log message -- which doesnt tell you anything about why the error occured!
- The bulk uploaded was adjusted so that it does not raise an Exception on one of these errors, rather it collects all the errors and returns them.  Then we can check and log all the errors.
- It can make for some lengthy logs, I considered truncating it past a certain length or aggregating it but ultimately decided that its better have all the information and it doesnt really matter how big the log files are, thats what they are there for.
- I also included a few small changes for ease of …
> SRCH-5864 Enhance logging ES Errors

- search_gov_crawler/benchmark.py
The output_target argument for benchmark -f was duplicated.  Once starting at line 211 and once starting at line 219, probably a merge conflict issue?  Anyway this means you cannot run `benchmark.py -f`.  This PR fixes that.
The other changes were auto formatting from by editor... more reason to get pylint (or something) in place i guess.
> Remove duplicate arg from Benchmark -f

- search_gov_crawler/search_gov_spiders/settings.py
- Added the 15MB limit for files and html content to download.  It is stopped prior the download started and definitely seems to be an improvement for domains where this happens. It doesn't always help but it seems like it could be one of a few things we do.  Here are some results.  Feel free to try it on some of these domains with and without the setting.
- When the setting is enabled and a download is encountered that is higher than the limit, it logs a WARN message like `Cancelling download of https://www.blm.gov/sites/default/files/docs/2021-04/BLM_WHB_ActivityBook_508_Dr1_031921.pdf: expected response size (15768110) larger than download max size (15728640).`
- The stats are from the scrapy stat collection module that prints at the end of each spider.
- The one time i saw a larger …
> SRCH-5908 download limit size

- search_gov_crawler/domains/config/domains_elasticsearch.libsonnet
- search_gov_crawler/domains/crawl-sites-development.json
- search_gov_crawler/domains/crawl-sites-production.json
- search_gov_crawler/domains/crawl-sites-staging.json
- Adds denypath to nei.nih.gov
If you are curious (like I was) to verify that a deny_path that includes part of the domain will in fact filter sites like the other deny paths we've added you could run a modified version of the domain and watch the CSV that it creates.
`scrapy crawl domain_spider -a allowed_domains=medialibrary.nei.nih.gov -a start_urls=https://medialibrary.nei.nih.gov/ -a output_target=csv -a depth_limit=5 -a deny_filter=medialibrary.nei.nih.gov/search`
> SRCH-5955 NIH deny path

- scripts/cache_tools.py
- search_gov_crawler/scheduling/jobstores.py
- search_gov_crawler/scheduling/redis.py
- search_gov_crawler/scheduling/schedulers.py
- search_gov_crawler/scrapy_scheduler.py
- tests/scheduling/conftest.py
- tests/scheduling/test_jobstores.py
- tests/scheduling/test_redis.py
- tests/scheduling/test_schedulers.py
- Added logging when jobs are added or removed from pending job store.
- Added `cache_tools.py` script with commands that allow someone to:
- show all jobs in the scheduler
- show all jobs in the pending queue
- clear all jobs from the pending queue
- show next run times for all scheduled jobs
- For logging, start the scheduler with some upcoming jobs, ensure you see logging like "Jobs in pending queue: #" when jobs are added to the queue.  You can kill -SIGINT the pid in another session to stop the jobs and then you should see the "Jobs in pending queue: #" decrease to match the jobs in the queue.
- For the script, ensure that local redis is running, venv is sourced, and try the following commands;
- `python scripts/cache_tools.py show-run-times` to show the next run times of schedule …
> SRCH-5987 Logging and cache tools

- .github/dependabot.yml
- search_gov_crawler/requirements.txt
In the dependabot PR #193, it wants to merge in the following updates:
| Package | From | To |
| --- | --- | --- |
| [elasticsearch](https://github.com/elastic/elasticsearch-py) | `8.17.1` | `9.0.0` |
| [pypdf](https://github.com/py-pdf/pypdf) | `5.3.1` | `5.4.0` |
| [python-dotenv](https://github.com/theskumar/python-dotenv) | `1.0.1` | `1.1.0` |
| [python-json-logger](https://github.com/nhairs/python-json-logger) | `3.2.1` | `3.3.0` |
| [scrapy-playwright](https://github.com/scrapy-plugins/scrapy-playwright) | `0.0.42` | `0.0.43` |
| [spidermon[monitoring]](https://github.com/scrapinghub/spidermon) | `1.23.0` | `1.24.0` |
| [typing-extensions](https://github.com/python/typing_extensions) | `4.12.2` | `4.13.2` |
Separately there is the PRs #191 and #192 for lxml-html-clean.
Here is what …
> SRCH-5989 Spider Dependency Updates

- search_gov_crawler/search_gov_spiders/middlewares.py
- tests/search_gov_spiders/test_middlewares.py
The goal of this story is to log an `ERROR` level message when a spider encounters an error with one or more of the start URLs.  This only happens now if there is a DNS, timeout, or other connection error.  If there is a 403 or the start URL redirects out of the domain, we sometimes get an INFO message but it does not get into the cloudwatch filters that show log messages where `levelname == ERROR`.
- Originally considered sub-classing the built-in `HttpErrorMiddleware`
- But since we already have a `SearchGovSpidersSpiderMiddleware` that is not really doing anything, I just added a check in `process_spider_exception` and logged the error there.  Seemed cleaner not to mess with the built-in middleware if I didn't have to.
- Also needed to update the `SearchGovSpidersOffsiteMiddleware` to …
> SRCH-5953 Log Errors When Occurs On Starting Urls

- search_gov_crawler/elasticsearch/convert_html_i14y.py
- search_gov_crawler/elasticsearch/convert_pdf_i14y.py
- search_gov_crawler/elasticsearch/i14y_helper.py
- tests/search_gov_spiders/test_i14y_helper.py
- tests/search_gov_spiders/test_i14y_html.py
- tests/search_gov_spiders/test_i14y_pdf.py
- Bug is we are seeing logs of errors about missing stop words files.  This is because for every doc we are trying to use the stopwords files from nltk and nltk does not support all the languages we support.
- Took two actions to fix this:
- For HTML, since `summarize_text` where the error occurs is not the primary method for generating the `description` or `tags` fields, I moved it into a conditional so that it only runs when if it is needed.  Many of the error messages were appearing for cases when newspaper4k or `convert_html_scrapy` already generated values and the `summarize_text` values would be discarded anyway.  I did not do the same for PDFs since `summarize_text` is a primary data-generation method there.
- Clarified the reasons why we return None from `summarize_text` and added …
> Srch 5932 cannot access stopwords bug

- search_gov_crawler/dap/datastore.py
- search_gov_crawler/elasticsearch/convert_html_i14y.py
- search_gov_crawler/elasticsearch/convert_pdf_i14y.py
- search_gov_crawler/elasticsearch/es_batch_upload.py
- search_gov_crawler/elasticsearch/i14y_helper.py
- search_gov_crawler/scheduling/redis.py
- search_gov_crawler/search_gov_spiders/helpers/domain_spider.py
- search_gov_crawler/search_gov_spiders/spiders/__init__.py
- search_gov_crawler/search_gov_spiders/spiders/domain_spider.py
- search_gov_crawler/search_gov_spiders/spiders/domain_spider_js.py
- tests/dap/test_dap_datastore.py
- tests/scheduling/test_redis.py
- tests/search_gov_spiders/test_elasticsearch.py
- tests/search_gov_spiders/test_encoding.py
- tests/search_gov_spiders/test_full_crawl.py
- tests/search_gov_spiders/test_helpers.py
- tests/search_gov_spiders/test_i14y_helper.py
- tests/search_gov_spiders/test_spider.py
- Added functionality so that the `dap_domain_visits_count` field on ES documents produced by spider contain either a 0 or a seven day average of the visits data extracted from DAP.
- Updated existing `get_avg_daily_visits_by_domain` to match logic discussed in the dev channel, use pipelines, and explicitly decode responses.
- In spider `__init__`, added helper function `get_domain_visits` that retrieves all domain and sub-domain data for all values in the `allowed_domains`, e.g. for a spider crawl of `gsa.gov` this will contain DAP records for `gsa.gov`, `a.gsa.gov`, `b.gsa.gov`, etc...
- Added default values of 0 to `dap_domain_visits_count` during document creation.
- In the `add_to_batch` method of `SearchGovElasticsearch`, added a function `update_dap_visits_to_document` that updates …
> SRCH-6052 DAP Visits On Doc

- search_gov_crawler/elasticsearch/convert_pdf_i14y.py
- search_gov_crawler/elasticsearch/es_batch_upload.py
- search_gov_crawler/search_gov_spiders/helpers/content.py
- search_gov_crawler/search_gov_spiders/settings.py
- tests/search_gov_spiders/test_benchmark.py
- tests/search_gov_spiders/test_elasticsearch.py
- tests/search_gov_spiders/test_scrapy_scheduler.py
This fixes the batch uploading by making it a sync type of operation. The elasticsearch python client still breaks the request up and sends it in parallel, so the speed trade of is not to significant. This is a race condition type of bug and it might randomly work or fail depending on batch size.
Here is a way to test it:
```bash
-a allowed_domains=govinfo.gov \
-a start_urls="https://www.govinfo.gov/media/100-2se.pdf" \
-a output_target=elasticsearch \
-a depth_limit=1 \
-a prevent_follow=True
-a allowed_domains=govinfo.gov \
-a start_urls="https://space-geodesy.nasa.gov/docs/2012/LRO-LR_xpondrWG_Nov2012_v2.pdf" \
-a output_target=elasticsearch \
-a depth_limit=1 \
-a prevent_follow=True
```
With this fix both should work now and …
> SRCH-6100: Fixed elasticsearch batch threading on upload

- search_gov_crawler/elasticsearch/es_batch_upload.py
- search_gov_crawler/requirements.txt
- tests/search_gov_spiders/test_elasticsearch.py
- Addresses error seen in production:
```
Traceback (most recent call last):
File "/opt/codedeploy-agent/deployment-root/a0ccbb6c-4ba1-41e7-89e4-d9031fd23edf/d-X2V6KZJOD/deployment-archive/search_gov_crawler/search_gov_spiders/pipelines.py", line 93, in _process_es_item
self._get_elasticsearch_client().add_to_batch(
File "/opt/codedeploy-agent/deployment-root/a0ccbb6c-4ba1-41e7-89e4-d9031fd23edf/d-X2V6KZJOD/deployment-archive/search_gov_crawler/elasticsearch/es_batch_upload.py", line 44, in add_to_batch
doc = convert_pdf(response_bytes=response_bytes, url=url, response_language=response_language)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/codedeploy-agent/deployment-root/a0ccbb6c-4ba1-41e7-89e4-d9031fd23edf/d-X2V6KZJOD/deployment-arc …
```
> SRCH-6010 PDF Bug

- search_gov_crawler/requirements.txt
- Addresses dependabot security finding
- Resolves #294 
- Resolves https://github.com/GSA-TTS/searchgov-spider/security/dependabot/106 
- I upgraded and tested manually.
- I picked a PDF heavy site and let it run for about 20 minutes. It didnt finish but it did scrape about 300 items.  I did not notice any problems.
```
-a allowed_domains=data.boem.gov \
-a start_urls="https://www.data.boem.gov/Other/FileRequestSystem/ScanPlans.aspx" \
-a output_target=elasticsearch \
-a depth_limit=2
```
- You can try this or another domain if you want.
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a re-review. If you cannot complete an item below, replace the checkbox with the ⚠️ `:warning:` emoji and explain …
> SRCH-6180 upgrade pypdf to v6
