GSA-TTS/searchgov-spider

.gitignore, .idea/inspectionProfiles/Project_Default.xml, .idea/inspectionProfiles/profiles_settings.xml, .idea/misc.xml, .idea/search-gov-spider.iml, .idea/vcs.xml, .idea/workspace.xml, search_gov_crawler/search_gov_spiders/settings.py, search_gov_crawler/search_gov_spiders/spiders/domain_spider.py
PR to implement broad crawling for scrapy spiders
- The project runs locally
- Tests pass (and location of tests in the project is considered)
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a re-review. If you cannot complete an item below, replace the checkbox with the ⚠️ :warning: emoji and explain why the step was not completed.
:warning:  Automated checks pass. If Code Climate checks do not pass, explain reason for failures:
-- Confluence page for how to enable on my fork gives me access denied. Otherwise I see RuboCop from code climate is for Ruby projects
Process Checks
:warning:  You have specified at least one "Reviewer".
-- I do not have write access to this repository therefore cannot assign a reviewer
=> SCRH-4761 Crawl multiple domains at a time (Implement broad crawling)

search_gov_crawler/requirements.txt, search_gov_crawler/search_gov_spiders/pip_settings.py, search_gov_crawler/search_gov_spiders/pipelines.py, search_gov_crawler/search_gov_spiders/settings.py, search_gov_crawler/search_gov_spiders/spiders/domain_spider.py, search_gov_crawler/search_gov_spiders/spiders/domain_spider_helper_functions.py, search_gov_crawler/search_gov_spiders/spiders/domain_spider_helper_variables.py
- Add scrapy-playwright and associated settings for javascript rendering
- Separated out helper functions/variables from domain-spider 
- Added deduplication pipeline
- Functionality should be the same as before; however a decrease in performance is to be expected. Settings can/should be tuned once EC2 resources are established. 
- New packages need to be installed and requirements.txt is updated
[comment]: # Unlike Travis CI, CircleCi does not test PRs with the combined changes of the PR and main. For this reason, it's necessary to …
=> SRCH-4763 render js playwright

search_gov_crawler/requirements.txt, search_gov_crawler/scrapy.cfg, search_gov_crawler/scrapyd.conf, search_gov_crawler/search_gov_spiders/pipelines.py, search_gov_crawler/setup.py
- Brief summary of the changes included in this PR
- Any additional information or context which may help the reviewer
[comment]: # Unlike Travis CI, CircleCi does not test PRs with the combined changes of the PR and main. For this reason, it's necessary to manually merge main into the PR branch, to ensure the combined code does not fail automated tests.
[comment]: # Including the Jira ticket ID in the commit message ensures that the commit, branch, and PR are linked automatically from the Jira ticket.
[comment]: # Github runs several …
=> SRCH-5427-IMPLEMENT-SCRAPY-D

README.md, search_gov_crawler/requirements.txt
Added scrapy playwright install instructions and updated requirements.txt file
[comment]: # Unlike Travis CI, CircleCi does not test PRs with the combined changes of the PR and main. For this reason, it's necessary to manually merge main into the PR branch, to ensure the combined code does not fail automated tests.
[comment]: # Including the Jira ticket ID in the commit message ensures that the commit, branch, and PR are linked automatically from the Jira ticket.
[comment]: # Github runs several automated checks, including Rubocop, via …
=> SRCH-4763-scrapy-playwright install instructions update

.github/dependabot.yml
Added a dependabot config... we can change it if this doesn't work for us but its usually a good idea to know about updates.  I separated the libraries into prod and dev since they probably have different requirements for inclusion.
I can't really test the entire config but i think this will work.
=> SRCH-5475 basic dependabot config

.circleci/config.yml, README.md, pyproject.toml, search_gov_crawler/requirements.txt, search_gov_crawler/setup.py, tests/integration_tests/test_scrapyd.py
- Upgrade to scrapyd 1.5.0 and scrapyd-client 2.0.0
- We no longer need the scrapyd-api library, its single use in `search_gov_crawler/setup.py` is no loner needed with scrapyd-client 2.0.0, so I removed it.
- Resolves #45 
- Added some basic "integration" tests where i actually run scrapyd and try out a few things.  I wanted to do more (deploy an egg, test out more of the APIs, perhaps run a scrape, do something with the UI, etc...) but it was taking a long time and thought something is better than nothing.
- Added a pytest extention library to help with running scripts in the tests.
- I had to ignore these when running in circle, i kept running into a connection refused error and wasn't able to figure it out.  If you run the entire test suite locally (`python -m pytest tests`) they will …
=> SRCH-5569 Upgrade Scrapyd

.circleci/config.yml, search_gov_crawler/scrapy.cfg, tests/integration_tests/test_scrapyd.py
Closes #47 
- I basically copied what I did in #47 to fix these tests.
- The AC is just that these tests will run successfully in circle.  You could also verify they run locally for you and nothing else is changed.
- Obviously these aren't really relevant at the moment but hopefully will become helpful once we start using scrapyd again.
=> SRCH-5659 Integration Tests

search_gov_crawler/benchmark.py, search_gov_crawler/search_gov_spiders/settings.py
- Finalized benchmark script after completing SRCH-5714.
- Allows for single run based on args or multiple runs based on file
You should be able to run using any or all of the CLI args, e.g.:
`python search_gov_crawler/benchmark.py -f crawl-sites-test.json`
or
`python benchmark.py -d example.com -u 'https://www.example.com'`
You should also be able to adjust the max spider jobs that run at the same time with the SCRAPY_MAX_WORKERS environment variable.
I didn't add unit tests for this file since its a benchmark and not part of the running code but if you think I should please let me know.
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a re-review. If you cannot complete an item below, replace the checkbox with the ⚠️ …
=> SRCH-5714 Benchmark Updates

.github/dependabot.yml, search_gov_crawler/requirements.txt, search_gov_crawler/search_gov_spiders/pipelines.py, tests/search_gov_spiders/test_urls_files_size.py
Not sure if you want to merge this or not but i made it a PR since it is an easy way to show the changes.
I fixed all the tests which mostly were not running due to:
* lack of pytest-mock import
* invalid patching of environment variables
* some weirdness with fixtures
I didn't do any checking for coverage or making sure things work, I simply got the tests working, mostly as the were.
=> Staging tests fix

tests/search_gov_spiders/test_urls_files_size.py
Fixed tests in staging.... they work, didnt investigate coverage.
=> fixes to tests

README.md, search_gov_crawler/benchmark.py, search_gov_crawler/scrapy_scheduler.py
- Documentation udpates related to pivot week.  Mostly around scheduler and benchmark.
=> SRCH-5791 README Update

cicd-scripts/app_install.sh, cicd-scripts/helpers/run_without_ui.sh, cicd-scripts/helpers/update_pythonpath.sh
- To sync staging change back into main
=> Staging to main 

search_gov_crawler/benchmark.py, search_gov_crawler/scrapy_scheduler.py, search_gov_crawler/search_gov_spiders/settings.py, search_gov_crawler/search_gov_spiders/utility_files/crawl-sites.json, tests/search_gov_spiders/test_helpers.py
As discussed this change takes care of a few known issues:
* Removes `drive.hhs.gov` from the crawl list
* Adds a 24 hour item timeout.
Also, in staging I noticed that jobs were not firing as expected... I realized that the settings used in `benchmark` to operate the schedule like a queue -- meaning five running slots and the rest of them wait for one to be finished before running -- were not applied to the `scrapy_scheduler` code.  Up until now we were not having successful deploy and thus not running scrapes from the `scrapy_scheduler` code, just from `benchmark` I made that change and deployed a test branch to confirm correct behavior.
* If you want to test the timeout the easiest way is to change the timeout value in the settings file to 1 and manually run a js domain.  It should exit …
=> SRCH-5816 Pre-Prod Adjustments

cicd-scripts/app_install.sh, cicd-scripts/helpers/fetch_env_vars.sh
- Supports #83 by providing environment variables needed to connect to elastic.
- Adds a new step to `app_install.sh` that fetches environment variables from parameter store and places them in the `.profile` for the search user.
- The step runs early in the process so that the variables are there for all following steps.
- The step calls a new helper script, `fetch_env_vars.sh`
- If there is an error in fetching or an error in applying the export statement the whole deploy should fail.
- For ES_HOSTS, i noticed that the values sometimes had spaces and brackets and quotes and sometimes not so i did some cleansing on that one to ensure we get consistent values.
- I removed the hard coded `SPIDER_PYTHON_VERSION` since it is now in param store (and was in ansible anyway)
- See …
=> Srch 5825 fetch env vars

search_gov_crawler/elasticsearch/es_batch_upload.py
- Slight improvements to logging noticed after staging run:
- Added message from spider logger saying we loaded records to ES and how many.  This helps because we can now track these requests per spider.
- Set the logging level to ERROR for elastic transport to get rid of generic log messages from elastic saying that it completed a POST.  Now that we have the spider-specific message we don't need these INFO messages.  Kept it at ERROR since we still want to know if something breaks.
- We will no longer see WARNING messages about insecure connections to elastic.  I added an argument to the connection to suppress these.
All other changes were just linter issues.
Running a test domain, e.g.
```
python benchmark.py -d travel.dod.mil -u https://www.travel.dod.mil -o elasticsearch
```
you …
=> SRCH-5829 add log message on write to elastic, filter extra messages

.github/dependabot.yml, search_gov_crawler/elasticsearch/install_nltk.py, search_gov_crawler/requirements.txt, tests/search_gov_spiders/test_i14y.py
This pull request adds tokenizing support for most all of our languages:
```
ALLOWED_LANGUAGE_CODE = { lang: True for lang in [ "ar", "bg", "bn", "ca", "cs", "da", "de", "el", "en", "es", "et", "fa", "fr", "he", "hi", "hr", "ht", "hu", "hy", "id", "it", "ja", "km", "ko", "lt", "lv", "mk", "nl", "pl", "ps", "pt", "ro", "ru", "sk", "so", "sq", "sr", "sw", "th", "tr", "uk", "ur", "uz", "vi", "zh" ]}
```
---
Testing:
1. Create/activate virtual environment and install dependences :
```bash
python -m venv venv
. venv/bin/activate
pip install -r ./search_gov_crawler/requirements.txt
```
2. Download more tokenizers:
```bash
python ./search_gov_crawler/elasticsearch/install_nltk.py
```
3. Create and run the following python file (or in console):
```python
from …
```
=> SRCH-5834: Tokenizer support for new languages

search_gov_crawler/requirements.txt, search_gov_crawler/search_gov_spiders/pipelines.py, tests/search_gov_spiders/test_urls_files_size.py
Safe removing/deleting the "html_content" and "output_target" fields (and values) from the Item
=> SRCH-5832: Clean item after processing

README.md, docs/advanced_setup_and_use.md, docs/architecture.md, docs/deployment.md, docs/deployments.md, docs/operations.md, docs/running_scrapydwebui.md
- The goal was to provide common commands that I run when doing operational things on the system.  That is here, at [docs/operations.md](https://github.com/GSA-TTS/searchgov-spider/compare/main...SRCH-5836_operational_docs#diff-ad74991b96593fdee570962fc5b1e319080abd55e16614f556f74b7de8fd02d1)
- I started to add all the operational commands to the main readme but it was already pretty long.  Once I broke out the operations page, I decided to break out a few other things.
- I got a little carried away and ended up trying to revamp the docs a bit.  Some stuff was outdated
- Moved everything except "About" and "Quick Start" out of the main readme.  Quick start is the minimum you have to do to get a scrape running.
- More complex things were moved to the "Advanced Setup and Use" page (or the …
=> SRCH-5836 Operational Docs

docker-compose.yml
- I was getting annoyed writing curl commands
- This works for me, not sure if its the best setup or not... i put this together based on some past projects + some googling... if there are some improvements please request.
=> Add Kibana to localdev docker

search_gov_crawler/benchmark.py, search_gov_crawler/search_gov_spiders/helpers/domain_spider.py, search_gov_crawler/search_gov_spiders/spiders/domain_spider.py, search_gov_crawler/search_gov_spiders/spiders/domain_spider_js.py, tests/search_gov_spiders/test_spider.py
- I noticed that i was sometimes running `scrapy crawl -a allowed_domains=example.com start_urls=https://www.example.com/` and the spider would give be weird errors, although not stop... this is because I did not include the `output_target` argument.
- This PR makes that argument required and adds validation that it should be one of the three valid values.
- It also moves the validation to a helper function since its the same for both spiders.
- I added the enforcement to benchmark as well since the domain and url are already required.
- Also, I noticed when running the JS spider it could not seralize requests using the on-disk store: `Unable to serialize request: <GET http://quotes.toscrape.com/> - reason: cannot pickle 'module' object - no more unserializable requests will be logged …
=> SRCH-5867 Enforce Output Target and Remove JS Errback

search_gov_crawler/domains/config/domains_endpoint.libsonnet, search_gov_crawler/domains/crawl-sites-development.json, search_gov_crawler/domains/crawl-sites-production.json, search_gov_crawler/domains/crawl-sites-staging.json
=> SRCH-5888: Added "nigms.nih.gov" to endpoint output target (scrutiny)

search_gov_crawler/elasticsearch/es_batch_upload.py
We are not ready to fully launch PDF support in production, so instead of officially creating a local environment variable, we decided to just hardcode it instead.
*We will need to completely remove this variable, once PDF is fully tested and we feel confident to deploy it to production
=> Added PDF feature flag support

search_gov_crawler/domains/config/domains_elasticsearch.libsonnet, search_gov_crawler/domains/crawl-sites-development.json, search_gov_crawler/domains/crawl-sites-production.json, search_gov_crawler/domains/crawl-sites-staging.json
Some of the job names were duplicates.  The scheduler would not start due to this.  I changed them so that they are unique and verified that i could start the scheduler locally.
We already have a story to add this unique check to our crawl sites validation... we should probably pull it sooner rather than later.  Also, I am going to create a story to see if we can add some sort of check at the end of the deploy that checks if the scheduler is running.  These deploys all "succeeded" but the scheduler did not start.
=> SRCH-5925 update names to unique value

search_gov_crawler/benchmark.py
- Changed shortcut from`-sd` to `-l`
- To test you can run a crawl using both options:
```
python search_gov_crawler/benchmark.py -d ed.gov -u https://www.ed.gov/ -o elasticsearch -l 1
OR
python search_gov_crawler/benchmark.py -d ed.gov -u https://www.ed.gov/ -o elasticsearch --depth_limit 1
```
=> SRCH-5927 Update CLI Arg Shortcut

search_gov_crawler/benchmark.py, search_gov_crawler/domains/config/domains_elasticsearch.libsonnet, search_gov_crawler/domains/crawl-sites-development.json, search_gov_crawler/domains/crawl-sites-production.json, search_gov_crawler/domains/crawl-sites-staging.json
Main to Staging Deploy
SRCH-5925 update name to unique value #155 
SRCH-5927 update cli arg shortcut #156
=> Staging Deploy

search_gov_crawler/domains/README.md, search_gov_crawler/domains/crawl-sites-development.md, search_gov_crawler/domains/crawl-sites-production.md, search_gov_crawler/domains/crawl-sites-staging.md, search_gov_crawler/domains/readschedule.py
Creates markdown files of schedules. 
Includes two functionalities: 
1) Create all schedules by running: 
```bash
cd search_gov_crawler/domains
python readschedule.py
```
2) Create individual schedules by running: 
```
cd search_gov_crawler/domains
python readschedule.py crawl-sites-development.json
python readschedule.py crawl-sites-staging.json
python readschedule.py crawl-sites-production.json   
```
The current markdowns are already included in this PR however you can delete them and run the instructions above to see functionality. 
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a re-review. If you cannot complete an item below, replace the checkbox with the ⚠️ `:warning:` emoji and explain why the step was not …
=> SRCH-5903 human schedule view

search_gov_crawler/domains/config/domains_elasticsearch.libsonnet, search_gov_crawler/domains/crawl-sites-development.json, search_gov_crawler/domains/crawl-sites-production.json, search_gov_crawler/domains/crawl-sites-staging.json
- Change domain for Guam Tricare
=> SRCH-5951 change domain for tricare_guam

search_gov_crawler/domains/config/domains_elasticsearch.libsonnet, search_gov_crawler/domains/crawl-sites-development.json, search_gov_crawler/domains/crawl-sites-development.md, search_gov_crawler/domains/crawl-sites-production.json, search_gov_crawler/domains/crawl-sites-production.md, search_gov_crawler/domains/crawl-sites-staging.json, search_gov_crawler/domains/crawl-sites-staging.md, search_gov_crawler/domains/readschedule.py
- Added several new deny paths based on behavior seen in prod.  Details in story https://cm-jira.usa.gov/browse/SRCH-5981
- Also updated readschedule so that it doesn't cause precommit to throw and error on the generated md files.
- Verify that there are no typos please.
=> SRCH-5981 Add more deny paths

scripts/cache_tools.py, search_gov_crawler/scheduling/jobstores.py, search_gov_crawler/scheduling/redis.py, search_gov_crawler/scheduling/schedulers.py, search_gov_crawler/scrapy_scheduler.py, tests/scheduling/conftest.py, tests/scheduling/test_jobstores.py, tests/scheduling/test_redis.py, tests/scheduling/test_schedulers.py
SRCH-5987 Logging and cache tools (#195)
=> Staging Release SRCH-5987

search_gov_crawler/domains/config/domains_elasticsearch.libsonnet, search_gov_crawler/domains/crawl-sites-production.json, search_gov_crawler/domains/crawl-sites-production.md, search_gov_crawler/domains/crawl-sites-staging.json, search_gov_crawler/domains/crawl-sites-staging.md
=> SRCH-5980: Batch 8 (fixed)

search_gov_crawler/domains/config/domains_elasticsearch.libsonnet, search_gov_crawler/domains/crawl-sites-production.json, search_gov_crawler/domains/crawl-sites-production.md, search_gov_crawler/domains/crawl-sites-staging.json, search_gov_crawler/domains/crawl-sites-staging.md
=> SRCH-5979: Batch 9 (fixed)

search_gov_crawler/domains/config/domains_elasticsearch.libsonnet, search_gov_crawler/domains/crawl-sites-production.json, search_gov_crawler/domains/crawl-sites-production.md, search_gov_crawler/domains/crawl-sites-staging.json, search_gov_crawler/domains/crawl-sites-staging.md
SRCH-5980: Batch 8 (fixed) (#197)
SRCH-5979: Fixed batch 9 (#198)
=> Staging Release SRCH-5980 SRCH-5979

search_gov_crawler/search_gov_spiders/sitemaps/sitemap_monitor.py
There might be a limit as to how many starting URLs we can have with scrapy. Adding batches with delay does not overload the resources by trying to do all the starting URLs at once
=> SRCH-6029: Batch processing new sitemap URLs

search_gov_crawler/elasticsearch/convert_html_i14y.py, search_gov_crawler/elasticsearch/es_batch_upload.py, search_gov_crawler/requirements.txt, search_gov_crawler/run_sitemap_monitor.py, search_gov_crawler/search_gov_spiders/extensions/json_logging.py, search_gov_crawler/search_gov_spiders/sitemaps/sitemap_finder.py, search_gov_crawler/search_gov_spiders/sitemaps/sitemap_monitor.py, search_gov_crawler/search_gov_spiders/spiders/domain_spider.py, search_gov_crawler/search_gov_spiders/spiders/domain_spider_js.py, tests/search_gov_spiders/test_extensions.py
SRCH-6030 update sitemap logging (#226)
SRCH-6029: Batch processing new sitemap URLs (#230) 
SRCH-6017: Only keeping OG images (#229)
=> Staging Release - DRAFT

.github/dependabot.yml, search_gov_crawler/requirements.txt, search_gov_crawler/search_gov_spiders/sitemaps/sitemap_monitor.py, tests/search_gov_spiders/test_sitemap_monitor.py
SRCH-6044: Added sitemap extension check (#235)
=> Staging Release - SRCH-6044

scripts/cache_tools.py
- Added `show-queued-urls` option to `cache_tools.py`.  This allows us to easily look into the job state requests queues to see which URLs are pending in the spider job.
- We don't have any tests any of these scripts, tested manually
- Start a crawl
- Capture the spider_id value from the logs
- cd to the scripts dir
- run `python cache_tools.py show-queued-urls -id <spider_id>`
- press enter to page through the urls 20 at a time
- to change the page size to 5 `python cache_tools.py show-queued-urls -id <spider_id> -p 5`
=> SRCH-6082 Update cache tools with new function

search_gov_crawler/elasticsearch/convert_pdf_i14y.py, tests/search_gov_spiders/test_i14y_pdf.py
- This solves the error seen in production:
```
Traceback (most recent call last):  
File "/opt/codedeploy-agent/deployment-root/a0ccbb6c-4ba1-41e7-89e4-d9031fd23edf/d-12QKXBJOC/deployment-archive/search_gov_crawler/search_gov_spiders/pipelines.py", line 93, in _process_es_item
self._get_elasticsearch_client().add_to_batch(
File "/opt/codedeploy-agent/deployment-root/a0ccbb6c-4ba1-41e7-89e4-d9031fd23edf/d-12QKXBJOC/deployment-archive/search_gov_crawler/elasticsearch/es_batch_upload.py", line 50, in add_to_batch
doc = convert_pdf(response_bytes=response_bytes, url=url, response_language=response_language)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/codedeploy-agent/deployment-root/a0ccbb6c-4ba1-41e7-89e4-d9031fd23edf/d-12QKXBJOC/deploy …
```
=> SRCH-6007 add check for indirectobject

scripts/cache_tools.py, search_gov_crawler/dap/datastore.py, search_gov_crawler/elasticsearch/convert_html_i14y.py, search_gov_crawler/elasticsearch/convert_pdf_i14y.py, search_gov_crawler/elasticsearch/es_batch_upload.py, search_gov_crawler/elasticsearch/i14y_helper.py, search_gov_crawler/scheduling/redis.py, search_gov_crawler/search_gov_spiders/helpers/domain_spider.py, search_gov_crawler/search_gov_spiders/spiders/__init__.py, search_gov_crawler/search_gov_spiders/spiders/domain_spider.py, search_gov_crawler/search_gov_spiders/spiders/domain_spider_js.py, tests/dap/test_dap_datastore.py, tests/scheduling/test_redis.py, tests/search_gov_spiders/test_elasticsearch.py, tests/search_gov_spiders/test_encoding.py, tests/search_gov_spiders/test_full_crawl.py, tests/search_gov_spiders/test_helpers.py, tests/search_gov_spiders/test_i14y_helper.py, tests/search_gov_spiders/test_i14y_pdf.py, tests/search_gov_spiders/test_spider.py
SRCH-6007 add check for IndirectObject (#259) 
SRCH-6052 DAP Visits On Doc (#262) 
SRCH-6082 update cache tools with new function (#252)
=> Staging Release - SRCH-6007 SRCH-6052 SRCH-6082

search_gov_crawler/elasticsearch/convert_pdf_i14y.py, search_gov_crawler/elasticsearch/es_batch_upload.py, search_gov_crawler/search_gov_spiders/helpers/content.py, search_gov_crawler/search_gov_spiders/settings.py, tests/search_gov_spiders/test_benchmark.py, tests/search_gov_spiders/test_elasticsearch.py, tests/search_gov_spiders/test_scrapy_scheduler.py
SRCH-6100: Fixed elasticsearch batch threading on upload (#264)
=> Staging Release - SRCH-6100

.github/dependabot.yml, scripts/README.md, scripts/query_tester.py, search_gov_crawler/requirements.txt, search_gov_crawler/search_gov_spiders/spiders/__init__.py
- We talked about trying a few things to [test query changes](https://docs.google.com/document/d/1pOx4FP6wZ9iOIL1WZM1fxXlHBmd9-jdMde1C5v-m8sQ/edit?tab=t.0#heading=h.vrg0i1i30ip2) 
- I was having trouble getting a complex query like the one the search app uses for search results to work inside Kibana
- So i wrote this script, the idea being we could sit with David and Ammie and run some searches and compare results.
- This uses the production search query which I adjusted the query to include the new scoring function AND to be a full government search
- So when you run this in prod, it should show you what the results will be if we make this change.
- I had to make the TYPE_CHECKING change since this script was causing a circular dependency due to my TypeVar that I added recently, but …
=> SRCH-6054 Testing Search Scoring

.github/dependabot.yml, scripts/README.md, scripts/query_tester.py, search_gov_crawler/requirements.txt, search_gov_crawler/search_gov_spiders/spiders/__init__.py
SRCH-6054 Testing Search Scoring (#265)
=> Staging Relase - SRCH-6054

scripts/query_tester.py
- Update to query tester script to allow for not just full govt search but for certain domains
- Came out of meeting with David and Ammie, they want to also be able to test impact of query changes on affiliates with multiple domains.
- No tests since we haven't been adding them for scripts.
- You may have to change the search terms below to get results for your local ES
- Original functionality remains unchanged, to search all govt for `apollo 11 moon mission` 
- `python scripts/query_tester.py full-govt-search apollo 11 moon mission`
- Results should appear from any domain in ES
- New functionality to limit search by a comma separated list of domains:
- `python scripts/query_tester.py affiliate-search apollo 11 moon mission --domains "nasa.gov,loc.gov"`
- Results should appear only from …
=> SRCH-6054 Add affiliate search and reduce duplication

scripts/query_tester.py, search_gov_crawler/elasticsearch/es_batch_upload.py, search_gov_crawler/requirements.txt, tests/search_gov_spiders/test_elasticsearch.py
SRCH-6010 PDF Bug (#277)
SRCH-6054 Add affiliate search and reduce duplication (#276)
=> Staging Release - SRCH-6010 SRCH-6054

search_gov_crawler/elasticsearch/convert_pdf_i14y.py, tests/search_gov_spiders/test_i14y_pdf.py
- Sometimes we get a `PDFStreamError` (or another subclass of `PDFReadError`) when trying to read in a PDF. This is not due to any fault of our own but rather an issue with the PDF.
- The change is to catch the error in this case and log a warning instead of raising the error.
- Also took a little time to improve test coverage in `covert_pdf_i14y.py`
- The PDF below does not fully load in the browser and after spot testing a few other PDFs that have the same issue I believe it is representative of PDF causing this issue.
- Run in main to see the error and then again in this branch to see the warning
```
-a allowed_domains=swpc.noaa.gov \
-a start_urls="https://www.swpc.noaa.gov/sites/default/files/images/u33/2013HarvinMooreSSHI_SolarSail_SpaceWeatherWorkshop_Bo …
```
=> SRCH-6012_pdf_bug log pdf read errors as warnings

search_gov_crawler/elasticsearch/convert_pdf_i14y.py, tests/search_gov_spiders/test_i14y_pdf.py
SRCH-6012_pdf_bug log pdf read errors as warnings (#279)
=> Staging Release - SRCH-6012

search_gov_crawler/domains/config/domains_elasticsearch.libsonnet, search_gov_crawler/domains/crawl-sites-development.json, search_gov_crawler/domains/crawl-sites-development.md, search_gov_crawler/domains/crawl-sites-production.json, search_gov_crawler/domains/crawl-sites-production.md, search_gov_crawler/domains/crawl-sites-staging.json, search_gov_crawler/domains/crawl-sites-staging.md
=> SRCH-6120: New URL changes

search_gov_crawler/elasticsearch/convert_pdf_i14y.py, tests/search_gov_spiders/test_i14y_pdf.py
- After some recent changes we started getting errors like `Failed to parse date string: D:191010911085603` and due to this were not loading documents.
- Additionally, when we encounter missing or invalid things in HTML docs we don't thrown errors (or warnings) we simply get what we can and move on.  Thats what I tried to implement here.
- We can still turn on debug to see messages locally or in lower environments but i dont think we really "care" about this enough to see it in log messages.
- Main changes are:
- update original regex with ^ and $ and Z to better match proper date strings
- add another regex option which is a bad date string, this is something that is pretty close but does not match
- finally allow for input that starts with "D:" but does not match either of the options …
=> SRCH-6129 Update PDF metadata date parsing logic

search_gov_crawler/domains/config/domains_elasticsearch.libsonnet, search_gov_crawler/domains/crawl-sites-development.json, search_gov_crawler/domains/crawl-sites-development.md, search_gov_crawler/domains/crawl-sites-production.json, search_gov_crawler/domains/crawl-sites-production.md, search_gov_crawler/domains/crawl-sites-staging.json, search_gov_crawler/domains/crawl-sites-staging.md, search_gov_crawler/elasticsearch/convert_pdf_i14y.py, tests/search_gov_spiders/test_i14y_pdf.py
SRCH-6120 New URL changes (#283) 
SRCH-6129 update metadata date parsing to reduce logging and to not prevent documents from loading (#282)
SRCH-6129 update regex to escape dash (#286)
=> Staging Release - SRCH-6120 SRCH-6129

search_gov_crawler/dap/connect.py
- Used suggested fix to address finding.
- Replaced `response.text` with other `response` attributes.
- Resolves https://github.com/GSA-TTS/searchgov-spider/security/code-scanning/2
- You can see the new error message by running the following:
```
export DATA_GOV_API_KEY="asdf"`
python search_gov_crawler/dap_extractor.py --run-now
```
=> SRCH-6181 CodeQL Finding

.github/pull_request_template.md
- Fix typo "fucntionalty" -> "functionality" in new testing section
- Nothing to test
=> Fix Typo in PR Template

search_gov_crawler/benchmark.py, search_gov_crawler/domains/config/domain_config.libsonnet, search_gov_crawler/domains/crawl-sites-development.json, search_gov_crawler/domains/crawl-sites-production.json, search_gov_crawler/domains/crawl-sites-staging.json, search_gov_crawler/domains/crawl-sites.jsonnet, search_gov_crawler/elasticsearch/convert_pdf_i14y.py, search_gov_crawler/run_sitemap_monitor.py, search_gov_crawler/search_gov_spiders/crawl_sites.py, search_gov_crawler/search_gov_spiders/sitemaps/sitemap_finder.py, search_gov_crawler/search_gov_spiders/sitemaps/sitemap_monitor.py, tests/search_gov_spiders/crawl-sites-test.json, tests/search_gov_spiders/test_content.py, tests/search_gov_spiders/test_crawl_sites.py, tests/search_gov_spiders/test_i14y_pdf.py, tests/search_gov_spiders/test_sitemap_finder.py, tests/search_gov_spiders/test_sitemap_monitor.py
SRCH-6139: New sitemap behavior/logic (#290) 
SRCH-6184 PDF Encryption Improvement (#304)
=> Staging Release - SRCH-6139 SRCH-6184

search_gov_crawler/search_gov_spiders/middlewares.py, tests/search_gov_spiders/test_middlewares.py
- **Problem:** For domains such as uscode.house.gov (and a few others) a different JSESSIONID value is being included in the URL for each new request.  This results in many instances of the same URL not being deuplicated and being ingested into Elasticsearch.
- **Solution:** Add a filter in the spider middleware so that if a URL contains a JESSIONID it is removed and the rest of the URL continues on.  
- You should be able to run a crawl to either elasticsearch or CSV and see that no URLs have a JSESSIONID in them.  I used csv like this but either should work:
```
-a allowed_domains=uscode.house.gov \
-a start_urls="https://uscode.house.gov" \
-a output_target=csv \
-a depth_limit=3
```
Please ensure you have addressed all concerns below before marking a PR …
=> SRCH-5972 Add Filtering To Remove Jsessionid From Urls

search_gov_crawler/domains/config/domains_elasticsearch.libsonnet, search_gov_crawler/domains/crawl-sites-production.json, search_gov_crawler/domains/crawl-sites-production.md, search_gov_crawler/domains/crawl-sites-staging.json, search_gov_crawler/domains/crawl-sites-staging.md
- Add deny path the glerl to prevent many `dat` files from attempting to be ingested.
- Review file for errors
=> SRCH-6186 glerl deny list

search_gov_crawler/domains/config/domains_elasticsearch.libsonnet, search_gov_crawler/domains/crawl-sites-production.json, search_gov_crawler/domains/crawl-sites-production.md, search_gov_crawler/domains/crawl-sites-staging.json, search_gov_crawler/domains/crawl-sites-staging.md
- Add new deny paths for usgs domains
- Verify files
=> SRCH-6197 Add Deny Paths

search_gov_crawler/domains/config/domains_elasticsearch.libsonnet, search_gov_crawler/domains/crawl-sites-production.json, search_gov_crawler/domains/crawl-sites-production.md, search_gov_crawler/domains/crawl-sites-staging.json, search_gov_crawler/domains/crawl-sites-staging.md
- Make Deny path more inclusive
- Verify file manually
=> SRCH-6198 Update Deny Path

search_gov_crawler/elasticsearch/convert_pdf_i14y.py
- Ive been seeing these ERROR messages in the logs: 
```json
{
"levelname": "ERROR",
"message": "Advanced encoding /SymbolSetEncoding not implemented yet",
"name": "pypdf._cmap"
}
```
- They have been annoying me since they don't appear to actually break anything and sometimes there are a lot of them.   Also they don't say which PDF triggers the log message so its been hard to find an example to test on.
- Finally found one on a random github page and raised the log level for that logger.
- It doesn't seem to really affect the content, at least in this one example I found so I thought its ok to suppress the message.
- Here is the file I found that triggers a log message
```
-a allowed_domains=github.com \
-a …
```
=> SRCH-6199 Increase logging level to avoid irrelevant error logging

search_gov_crawler/elasticsearch/convert_pdf_i14y.py
SRCH-6199 increase logging level to avoid irrelevant error logging (#314)
=> Staging Release SRCH-6199 
